dist: trusty

language: php
php:
  - '7.1'

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - psql -c 'create database travis_ci_test;' -U postgres
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - php artisan serve &

services:
  - postgresql

addons:
  postgresql: "9.4"

notifications:
    on_success: never
    on_failure: always